// <auto-generated />
using EconomicMappingAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EconomicMappingAPI.Migrations
{
    [DbContext(typeof(EconomicMappingAPIContext))]
    [Migration("20200818175241_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EconomicMappingAPI.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GDP");

                    b.Property<string>("MainExport");

                    b.Property<string>("MainImport");

                    b.Property<string>("Name");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            GDP = 2,
                            MainExport = "coffee",
                            MainImport = "avocodos",
                            Name = "California"
                        },
                        new
                        {
                            StateId = 2,
                            GDP = 3,
                            MainExport = "Cowboys",
                            MainImport = "Capitalism",
                            Name = "Texas"
                        },
                        new
                        {
                            StateId = 3,
                            GDP = 23,
                            MainExport = "Spring Break",
                            MainImport = "Freshmen",
                            Name = "Flordia"
                        },
                        new
                        {
                            StateId = 4,
                            GDP = 2,
                            MainExport = "COWS",
                            MainImport = "Nothing",
                            Name = "Wisconsin"
                        },
                        new
                        {
                            StateId = 5,
                            GDP = 23542,
                            MainExport = "Wine",
                            MainImport = "California",
                            Name = "Oregon"
                        },
                        new
                        {
                            StateId = 6,
                            GDP = 1,
                            MainExport = "Moonshine",
                            MainImport = "The bible",
                            Name = "Alabama"
                        },
                        new
                        {
                            StateId = 7,
                            GDP = 4,
                            MainExport = "Corn",
                            MainImport = "Moonshine",
                            Name = "Arkansas"
                        },
                        new
                        {
                            StateId = 8,
                            GDP = 0,
                            MainExport = "Fish",
                            MainImport = "IG Influencers",
                            Name = "Alaska"
                        },
                        new
                        {
                            StateId = 9,
                            GDP = 2,
                            MainExport = "Sand",
                            MainImport = "Heat",
                            Name = "Arizona"
                        },
                        new
                        {
                            StateId = 10,
                            GDP = 434,
                            MainExport = "Skiing",
                            MainImport = "Snow",
                            Name = "Colorado"
                        },
                        new
                        {
                            StateId = 11,
                            GDP = 34,
                            MainExport = "Penguins",
                            MainImport = "CO2",
                            Name = "Connecticut"
                        },
                        new
                        {
                            StateId = 12,
                            GDP = 3,
                            MainExport = "Babies",
                            MainImport = "Elephants",
                            Name = "Delaware"
                        },
                        new
                        {
                            StateId = 13,
                            GDP = 3,
                            MainExport = "Racism",
                            MainImport = "Nothing, Leeches",
                            Name = "Georgia"
                        },
                        new
                        {
                            StateId = 14,
                            GDP = 5,
                            MainExport = "Colonialism",
                            MainImport = "Colonialism",
                            Name = "Hawaii"
                        },
                        new
                        {
                            StateId = 15,
                            GDP = 678,
                            MainExport = "rebels",
                            MainImport = "Rebel flags",
                            Name = "Idaho"
                        },
                        new
                        {
                            StateId = 16,
                            GDP = 456,
                            MainExport = "Al Capone",
                            MainImport = "Chicago",
                            Name = "Illinois"
                        },
                        new
                        {
                            StateId = 17,
                            GDP = 45,
                            MainExport = "Hoosiers",
                            MainImport = "Corn",
                            Name = "Indiana"
                        },
                        new
                        {
                            StateId = 18,
                            GDP = 56,
                            MainExport = "Hawkeyes",
                            MainImport = "Corn",
                            Name = "Iowa"
                        },
                        new
                        {
                            StateId = 19,
                            GDP = 789,
                            MainExport = "Dustbowl",
                            MainImport = "Mahomes",
                            Name = "Kansas"
                        },
                        new
                        {
                            StateId = 20,
                            GDP = 892,
                            MainExport = "Moonshine",
                            MainImport = "Pickles",
                            Name = "Kentucky"
                        },
                        new
                        {
                            StateId = 21,
                            GDP = 987,
                            MainExport = "CrawDads",
                            MainImport = "Oil",
                            Name = "Louisiana"
                        },
                        new
                        {
                            StateId = 22,
                            GDP = 345,
                            MainExport = "Crabbies",
                            MainImport = "Tourists",
                            Name = "Maine"
                        },
                        new
                        {
                            StateId = 23,
                            GDP = 45,
                            MainExport = "Donald Trump",
                            MainImport = "Corruption",
                            Name = "Maryland"
                        },
                        new
                        {
                            StateId = 24,
                            GDP = 89,
                            MainExport = "CAHS",
                            MainImport = "Robbery",
                            Name = "Massachusetts"
                        },
                        new
                        {
                            StateId = 25,
                            GDP = 56,
                            MainExport = "Eminem",
                            MainImport = "tolerable weather",
                            Name = "Michigan"
                        },
                        new
                        {
                            StateId = 26,
                            GDP = 74,
                            MainExport = "OOPE",
                            MainImport = "the Minnesota Nice",
                            Name = "Minnesota"
                        },
                        new
                        {
                            StateId = 27,
                            GDP = 4,
                            MainExport = "Muddy Water",
                            MainImport = "Cotton",
                            Name = "Mississippi"
                        },
                        new
                        {
                            StateId = 28,
                            GDP = 67,
                            MainExport = "Fiscal Disaster",
                            MainImport = "Books",
                            Name = "Missouri"
                        },
                        new
                        {
                            StateId = 29,
                            GDP = 5,
                            MainExport = "Grizzlies",
                            MainImport = "Glaciers",
                            Name = "Montana"
                        },
                        new
                        {
                            StateId = 30,
                            GDP = 6,
                            MainExport = "Unhealthy cows",
                            MainImport = "Not Deodorant",
                            Name = "Nebraska"
                        },
                        new
                        {
                            StateId = 31,
                            GDP = 7,
                            MainExport = "Gambling",
                            MainImport = "Regrettable Marriages",
                            Name = "Nevada"
                        },
                        new
                        {
                            StateId = 32,
                            GDP = 8,
                            MainExport = "Peter Griffin",
                            MainImport = "Adam West",
                            Name = "New Hampshire"
                        },
                        new
                        {
                            StateId = 33,
                            GDP = 9,
                            MainExport = "Wants to be New York",
                            MainImport = "New York",
                            Name = "New Jersey"
                        },
                        new
                        {
                            StateId = 34,
                            GDP = 1,
                            MainExport = "Meth",
                            MainImport = "Cartel",
                            Name = "New Mexico"
                        },
                        new
                        {
                            StateId = 35,
                            GDP = 2,
                            MainExport = " the Mafia",
                            MainImport = "RICO",
                            Name = "New York"
                        },
                        new
                        {
                            StateId = 36,
                            GDP = 3,
                            MainExport = "Charlotte",
                            MainImport = "Beer",
                            Name = "North Carolina"
                        },
                        new
                        {
                            StateId = 37,
                            GDP = 4,
                            MainExport = "Trash",
                            MainImport = "Flat AF",
                            Name = "North Dakota"
                        },
                        new
                        {
                            StateId = 38,
                            GDP = 5,
                            MainExport = "What even is a Buckeye?",
                            MainImport = "Radioactive River Water",
                            Name = "Ohio"
                        },
                        new
                        {
                            StateId = 39,
                            GDP = 6,
                            MainExport = "Home, HOME ON THE RANGE",
                            MainImport = "Where the deer and the antelope PLAY",
                            Name = "Oklahoma"
                        },
                        new
                        {
                            StateId = 40,
                            GDP = 7,
                            MainExport = "Philly Cheese STEAK",
                            MainImport = "Cheese, Steak, and Philly",
                            Name = "Pennsylvania"
                        },
                        new
                        {
                            StateId = 41,
                            GDP = 8,
                            MainExport = "Road",
                            MainImport = "Providence!!!!!!",
                            Name = "Rhode Island"
                        },
                        new
                        {
                            StateId = 42,
                            GDP = 9,
                            MainExport = "Cotton",
                            MainImport = "an uncomfortable heritage",
                            Name = "South Carolina"
                        },
                        new
                        {
                            StateId = 43,
                            GDP = 1,
                            MainExport = "Highway Bandits",
                            MainImport = "Probably stolen goods",
                            Name = "South Dakota"
                        },
                        new
                        {
                            StateId = 44,
                            GDP = 2,
                            MainExport = "Country Music",
                            MainImport = "Run away wives",
                            Name = "Tennessee"
                        },
                        new
                        {
                            StateId = 45,
                            GDP = 3,
                            MainExport = "Mormons",
                            MainImport = "Nothing, they already have it",
                            Name = "Utah"
                        },
                        new
                        {
                            StateId = 46,
                            GDP = 4,
                            MainExport = "BERNIE",
                            MainImport = "FEEL THE BERN",
                            Name = "Vermont"
                        },
                        new
                        {
                            StateId = 47,
                            GDP = 5,
                            MainExport = "Land of lovers",
                            MainImport = "Flowers, wine, and chocolates",
                            Name = "Virginia"
                        },
                        new
                        {
                            StateId = 48,
                            GDP = 6,
                            MainExport = "Marijuana",
                            MainImport = "Nothing, Please go away",
                            Name = "Washington"
                        },
                        new
                        {
                            StateId = 49,
                            GDP = 7,
                            MainExport = "Coal",
                            MainImport = "I've got the black lung, Pa",
                            Name = "West Virginia"
                        },
                        new
                        {
                            StateId = 50,
                            GDP = 8,
                            MainExport = "Buffalo",
                            MainImport = "Popcorn",
                            Name = "Wyoming"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
